### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by TheConceptBoy** [DLzer/Zork#2]
Good day.
Was wondering if this project is completed or abandoned?
I tried playing it. Put the leaflet in the bag, then read the leaflet, but it doesn't seem to parse the command.

**Comment by DLzer** [comment]
Hey, sorry for the delay. Thank you for taking the time to try the game. The original game engine was around 90% done and contained a few bugs. One of which you found. I'm actually in the process of re-writing the game engine and game objects to be a lot cleaner.

If you would like to help with this repository you can check out the `feat/GameEngine` branch which contains the newer version of the core game engine code. Otherwise, please be patient while I wrap up version 2.

Thank you!

**Comment by DLzer** [comment]
New beta is released. Mind you some bugs are present but I will be working through them within the next few weeks.
