### ISSUE TITLE
Move Rug not working

### ISSUE THREAD

**Issue by LucAndre91** [DLzer/Zork#3]
Hi 

First of all thanks for let us using the java for Zork. Perfect for our Easter Egg Project. I tried to solve the Adventure but at the point "MOVE RUG" it is not working? Is there any Issue with it? 

Do you have a Walkthrough of your Version of ZORK?

Thanks

**Comment by LucAndre91** [comment]
It is always saying Oh no, that doesn't look right! I tried many combinations:

Move Rug
Move Oriental Rug
Move the Rug
Pull / Push The Rug
Pull / Push Rug 
and many more!

![image](https://user-images.githubusercontent.com/72881041/152787884-0c9da121-5b80-4536-8208-5aa667d2f69a.png)

**Comment by DLzer** [comment]
First off, thank you for your interest in ZORK. Additionally, thanks for the email. I will be posting the response here as well for transparency, and for others to see.

Sorry to hear you've run into an issue. As mentioned in the readme ZORK is currently in beta and still has some bugs.
About 2 months ago I pushed a v2 of the game's movement/item/room engine which included a handful of updates. I believe where I left off were the push/pull actions. Which unfortunately is exactly the issue you've run into!

Unfortunately my time is a bit limited at the moment with other projects. I can make some time to add the additional movement features in hopefully come this weekend. Otherwise, if you would like to take a stab at furthering the development by contributing feel free to do so.

The file that would need to be updated would be:
https://github.com/DLzer/Zork/blob/master/assets/js/Domain/GameEngine/GameEngine.js
Which is the games action engine. PullAction/PushAction/MoveAction need to be added. 
These actions need to be linked to the livingRoomRug, which is a Room, and not an Item, as shown here:
https://github.com/DLzer/Zork/blob/master/assets/js/Domain/Room/Room.js#L117

**Comment by DLzer** [comment]
This has been fixed in release [v0.9.5-beta](https://github.com/DLzer/Zork/releases/tag/v0.9.5-beta)!

Thank you for bringing this issue to my attention 👍

**Comment by LucAndre91** [comment]
Hi Dillon

I just received the update. Question: is it now fully useable?

Freundliche Grüsse
Luca Koller

On 7 Feb 2022, at 17:37, Dillon Lomnitzer ***@***.***> wrote:

﻿

First off, thank you for your interest in ZORK. Additionally, thanks for the email. I will be posting the response here as well for transparency, and for others to see.

Sorry to hear you've run into an issue. As mentioned in the readme ZORK is currently in beta and still has some bugs.
About 2 months ago I pushed a v2 of the game's movement/item/room engine which included a handful of updates. I believe where I left off were the push/pull actions. Which unfortunately is exactly the issue you've run into!

Unfortunately my time is a bit limited at the moment with other projects. I can make some time to add the additional movement features in hopefully come this weekend. Otherwise, if you would like to take a stab at furthering the development by contributing feel free to do so.

The file that would need to be updated would be:
https://github.com/DLzer/Zork/blob/master/assets/js/Domain/GameEngine/GameEngine.js
Which is the games action engine. PullAction/PushAction/MoveAction need to be added.
These actions need to be linked to the livingRoomRug, which is a Room, and not an Item, as shown here:
https://github.com/DLzer/Zork/blob/master/assets/js/Domain/Room/Room.js#L117

**Comment by DLzer** [comment]
Hey there! The game itself does need more rooms added, but the mechanics and engine are there. However, I was able to fix the reported issue you were having with moving the rug 😄

**Comment by LucAndre91** [comment]
Hi Dillon

Hope you are good?

I just managed how to add new rooms etc. so I can do it maybe by my own to the finish. Will inform you so you could have the final code and see if there are any fails in it 😊

Cheers
Luc

Von: Dillon Lomnitzer ***@***.***>
Datum: Dienstag, 19. Juli 2022 um 02:00
An: DLzer/Zork ***@***.***>
Cc: LucAndre91 ***@***.***>, Author ***@***.***>
Betreff: Re: [DLzer/Zork] Move Rug not working (Issue #3)

Hey there! The game itself does need more rooms added, but the mechanics and engine are there. However, I was able to fix the reported issue you were having with moving the rug 😄

**Comment by DLzer** [comment]
Awesome! If you would like to contribute feel free to make a Pull Request with the new code!
